trigger:
- main  # Change to the branch where your code is

pr:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    terraform init
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'
  workingDirectory: $(Build.SourcesDirectory)

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: $(Build.SourcesDirectory)
